[package]
name = "client-server-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
steganography = "1.0.2"
image = "0.21"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "decoder"
path = "src/decoder.rs"
